NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/ca.anacaudit.anac.gov.br-cert.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/ca.anacaudit.anac.gov.br.pem
    OrganizationalUnitIdentifier: peer
